// Objective-C API for talking to hello Go package.
//   gobind -lang=objc hello
//
// File is generated by gobind. Do not edit.

#ifndef __Hello_H__
#define __Hello_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* _Nonnull HelloHello_world(void);

#endif
